### PR TITLE
Remove autoprepended data from .create_ref error messages 

### LINKED ISSUE #675: create_ref error message can be unhelpful
`Octokit::Client.create_ref` will return a message from the API about how to format refs verbatim:

```
POST https://api.github.com/repos/foo/bar/git/refs: 422 - Reference name must contain at least three slash-separated components. // See: https://developer.github.com/v3/git/refs/#create-a-reference
```

But this message isn't very helpful, because Octokit will prepend `refs/` to anything given. If one follows the error message's advice, sending in `refs/heads/whatever`, the result is:

```
POST https://api.github.com/repos/foo/bar/git/refs: 422 - refs//refs/heads/potential-master-foo is not a valid ref name. // See: https://developer.github.com/v3/git/refs/#create-a-reference
```

Since we're going to pass the error message back to the client, and we're going to edit the data the client gives us, should we strip a leading `refs/` from client input? I'm don't think `refs/refs` is ever valid anyway, and it would make following the error message's advice work.

### PR DESCRIPTION
**Pull request by joeyw**
Remove "refs/" that is added by octokit automatically from any error messages

Fixes #675

### CODE REVIEW

**Comment by gjtorikian** [comment]
Hmm. Is `refs/` an addition from Octokit, or the actual API? If the latter it seems the problem should be fixed upstream.

**Comment by joeyw** [comment]
It's added by octokit https://github.com/octokit/octokit.rb/blob/28a594ff371ff3faf8ec50dd25bd65bd779ff43f/lib/octokit/client/refs.rb#L50

**Comment by pengwynn** [comment]
Thanks, @joeyw. I think we were wanting to fix this on the input side. Something like:

```ruby
def create_ref(repo, ref, sha, options = {})
  ref = "refs/#{ref}" unless ref =~ %r(refs/)
  parameters = {
    :ref  => ref,
    :sha  => sha
  }
  ...
```

**Comment by joeyw** [comment]
Well that is a lot easier. Nothing like fixing the wrong problem :)

**Comment by pengwynn** [comment]
Looks good @joeyw. :cake:

**Comment by bhuga** [comment]
:heart:

**Pull request merged**
