### PR TITLE
Add the ability to populate the review request with users

### PR DESCRIPTION
**Pull request by jblac**
I had the need to automatically assign review_requests when users missed it, in order to do that I added that one method to the client.

Not sure how to properly do a spec for this so I did leave that out if this is of interest to the maintainer(s).

### CODE REVIEW

**Comment by kytrinyx** [comment]
Hey! This looks pretty good. There are a couple of things we'd need in order to merge it.

1. The endpoint requires a preview media type (see: https://developer.github.com/v3/pulls/review_requests/#create-a-review-request)
1. We're going to need tests.

You can check out this PR for guidance on how to do these things: https://github.com/octokit/octokit.rb/pull/928

**Comment by jblac** [comment]
@kytrinyx thanks for that info, I'll get this pr updated asap with the necessary elements.

**Comment by tarebyte** [comment]
Gentle bump @jblac are you still interested in taking this over the finish line?

**Comment by nickfloyd** [comment]
Hey, @jblac thank you for the effort here.  Given this has been out for close to 5 years and many changes have been added since this was first introduced, I am going to close this PR and mark it as stale.  If you feel strongly about this needing to be implemented please feel free to reopen and make the changes stated above and we'll do what we can to get it merged in.  Thanks again!

**Pull request closed without merging**
