### PR TITLE
Use 'line' instead of 'position'

### LINKED ISSUE #1565: [FEAT]: Add support line property to create_pull_request_comment
### Describe the need

Hi🙋

I want to post a multiline comment using `create_pull_request_comment`, but it seems like I need to use 'line' instead of 'position'. [The API reference](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-comment) mentions that 'position' is deprecated and recommends using 'line' instead. Do you know if there are any plans to support this change? If I missed something, I apologize.

### SDK Version

_No response_

### API Version

2022-11-28

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tick-taku**
Resolves #1565 

----

### Before the change?

* The deprecated 'position' is being used in create_pull_request_comment.(https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-comment)

### After the change?

* Use 'line' instead of 'position'.

### Other information

* I changed to specify parameters required for multiline comments, such as 'start_line', in the 'options'.

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
I've approved the Actions runs; thank you for submitting! I'm slightly torn about this: I think this is a breaking change since the signature of `create_pull_request_comment` is changing. Would it be better to provide an override or mark the current method as deprecated first and then remove it entirely in a new major version after?

**Comment by tick-taku** [comment]
Well...You're right! It may not be possible to provide an override because we're just changing the parameter name, and the type remains the same. So I think we have no choice but to release it in the next major version.
In terms of just using it, you can still use it as is since the type remains the same, and it's not using keyword arguments.
What do you think would be a good course of action?

**Comment by kfcampbell** [comment]
Hmm...I'm not loving any of these options, really. Perhaps the best thing to do is note in comments/docs that "position" will go away in favor of "line" in the next major version, and save this PR up for when we cut a new major version.

**Comment by tick-taku** [comment]
I see, understood! Thanks!
We will put it on hold until the next major version. I will submit a Pull Request with the additional comments.

**Comment by kfcampbell** [comment]
When we merge #1596, we can/should also take this PR before cutting a breaking change.

**Review by kfcampbell — APPROVED** [review]
I think the deprecation notice has been baking long enough and we can release this breaking change now!

**Pull request merged**
