### PR TITLE
Add support for user suspending and unsuspending

### PR DESCRIPTION
**Pull request by stetsenko**
Github API reference (requires Github Enterprise ):
 - https://developer.github.com/v3/users/administration/#suspend-a-user
 - https://developer.github.com/v3/users/administration/#unsuspend-a-user

### CODE REVIEW

**Comment by niralntrivedi** [comment]
Being a GHE Admin, this will be incredibly helpful. Thanks @stetsenko for making this change. 

:+1:

**Comment by jehaan7** [comment]
Can't wait to use this feature. Good Job!

**Comment by shaded2** [comment]
:+1:

**Comment by mayurva** [comment]
:+1: Would be an Useful addition.

**Comment by stetsenko** [comment]
@pengwynn would you mind providing feedback on this PR? For instance, do you think it would be possible to start introducing more of Enterprise API support in octokit? Thanks!

**Comment by pengwynn** [comment]
@stetsenko Sorry, this one fell through the cracks.

We're working on really robust Enterprise support in Octokit and I expect we'll open a PR to get some feedback on that really soon. Stay tuned. :tv:

**Comment by pengwynn** [comment]
Pulled into #582 and merged. :sparkles:

**Pull request closed without merging**
