### PR TITLE
Fix missing and broken links in README table of contents

### LINKED ISSUE #1514: [DOCS]: README table of contents contains a broken link to Installation section
### Describe the need

`README` table of contents contains a broken link to `Installation` section and should be updated to reflect the proper hyperlink.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1515: [DOCS]: README table of contents contains a missing entry for "Default results per_page"
### Describe the need

`README` table of contents contains a missing entry for `Default results per_page`, this entry should be added to the table of contents

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jarvl**
Resolves #1514 
Resolves #1515 

----

### Before the change?

* `README.md` table of contents contains a broken link to `Installation` and a missing entry for `Default results per_page`.

### After the change?

* `README.md` table of contents contains a working link to `Installation` and an entry (with working hyperlink) to `Default results per_page`.

### Other information

* None

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by Jarvl** [comment]
The template states `Please add the corresponding label for change this PR introduces`, however I am unable to add a label to this PR.

**Review by kfcampbell — APPROVED** [review]
This looks great, thanks!

**Comment by kfcampbell** [comment]
Hmm...I'm not sure why the required checks aren't running, which is blocking me from merging this. Perhaps an empty commit will trigger them.

**Comment by kfcampbell** [comment]
Oh shoot, the build issue is unrelated and needs to be solved for multiple PRs.

**Pull request merged**
