### PR TITLE
Support getting milestones using a repository id

### PR DESCRIPTION
**Pull request by stmllr**
Milestones of a repository can be queried using the repository id.

### CODE REVIEW

**Comment by stmllr** [comment]
If you like to have tests for this, please let me know. I left them out intentionally because
 * I did not find any other spec which uses the repository id for queries.
 * Repository.path is covered itself within `repository_spec.rb`
 * using repository id is not documented in GitHub API

**Comment by tarebyte** [comment]
@stmllr it would be nice to have a few tests, just to ensure we don't add a regression in later.

Here is an example for you https://github.com/octokit/octokit.rb/blob/3dcb9184cba56f591d7b278dfd3c2db04de95a05/spec/octokit/client/repositories_spec.rb#L50-L54

**Comment by stmllr** [comment]
@tarebyte Here we go...

**Comment by stmllr** [comment]
any chance this PR gets merged?

**Comment by pengwynn** [comment]
Nice. Thanks, @stmllr.

**Pull request merged**
