### PR TITLE
Add support for Community Profile API

### PR DESCRIPTION
**Pull request by kaorimatz**
This PR adds support for the [Community Profile API](https://developer.github.com/v3/repos/community/).

Resolves https://github.com/octokit/octokit.rb/issues/891

### CODE REVIEW

**Comment by kytrinyx** [comment]
@kaorimatz I'm so sorry we missed this.

The build is failing -- would you take a look to see if you can get it working? If you're stuck please holler, and we'll help you sort it out.

**Comment by kaorimatz** [comment]
@kytrinyx Thank you so much for taking a look. I have updated the branch with master and the build passed.

**Comment by kytrinyx** [comment]
Thank you @kaorimatz!

**Comment by kaorimatz** [comment]
Thank you very much!

**Pull request merged**
